name: ml-for-bem-sampling

channels:
  - plotly
  - conda-forge
dependencies:
  - ipywidgets
  - nbformat
  - plotly
  - fiona
  - numpy
  - python=3.8
  - requests
  - google-cloud-storage
  - h5py
  - pytables
  - pip
  - geopandas
  
